ARG TERRAFORM_VERSION=v1.9
FROM quay.io/cloudnativetoolkit/cli-tools-core:${TERRAFORM_VERSION}-v2.1.0-fedora

ARG TARGETPLATFORM

ENV TF_CLI_ARGS_apply="-parallelism=6"

USER root

## AWS cli
RUN dnf install -y \
        awscli && \
    dnf clean all

## Azure cli
RUN dnf install -y \
        python3 \
        pip3 \
        gcc \
        musl-devel \
        python3-devel \
        libffi-devel \
        openssl-devel \
        cargo \
        make && \
    dnf clean all && \
    pip3 install --upgrade --break-system-packages pip

USER devops

# Azure cli
RUN pip3 install --break-system-packages azure-cli

# Install the ibmcloud cli

USER root

RUN curl -fsSL https://clis.cloud.ibm.com/install/linux | sh && \
    ibmcloud plugin install container-service -f && \
    ibmcloud plugin install container-registry -f && \
    ibmcloud plugin install observe-service -f && \
    ibmcloud plugin install vpc-infrastructure -f && \
    ibmcloud config --check-version=false && \
    chown -R devops ${HOME}/.bluemix && \
    chmod -R g=u ${HOME}/.bluemix

USER devops
