ARG TERRAFORM_VERSION=v1.9
FROM quay.io/cloudnativetoolkit/cli-tools-core:${TERRAFORM_VERSION}-v2.0.3-alpine

ARG TARGETPLATFORM

ENV TF_CLI_ARGS_apply="-parallelism=6"

USER root

## AWS cli
RUN apk add --no-cache --force-broken-world \
        aws-cli && \
    rm -rf /var/cache/apk/*

## Azure cli
RUN apk add --no-cache --force-broken-world \
        python3 \
        py3-pip \
        gcc \
        musl-dev \
        python3-dev \
        libffi-dev \
        openssl-dev \
        cargo \
        make && \
    rm -rf /var/cache/apk/* && \
    pip3 install --upgrade --break-system-packages pip

USER devops

RUN pip3 install --break-system-packages azure-cli

# Install the ibmcloud cli
RUN curl -fsSL https://clis.cloud.ibm.com/install/linux | sh && \
    ibmcloud plugin install container-service -f && \
    ibmcloud plugin install container-registry -f && \
    ibmcloud plugin install vpc-infrastructure -f && \
    ibmcloud config --check-version=false && \
    chmod -R g=u ${HOME}
