ARG TERRAFORM_VERSION=v1.2
FROM quay.io/cloudnativetoolkit/cli-tools-core:${TERRAFORM_VERSION}-v1.4.6-alpine

ARG TARGETPLATFORM

ENV TF_CLI_ARGS_apply="-parallelism=6"

## AWS cli
RUN sudo apk add --no-cache \
        python3 \
        py3-pip \
    && sudo pip3 install --upgrade pip \
    && sudo pip3 install awscli \
    && sudo rm -rf /var/cache/apk/* \
    && aws --version

## Azure cli
RUN sudo apk add gcc musl-dev python3-dev libffi-dev openssl-dev cargo make python3 py3-pip \
    && sudo pip3 install --upgrade pip \
    && sudo pip3 install azure-cli \
    && sudo rm -rf /var/cache/apk/* \
    && az --version

# Install the ibmcloud cli
RUN curl -fsSL https://clis.cloud.ibm.com/install/linux | sh && \
    ibmcloud plugin install container-service -f && \
    ibmcloud plugin install container-registry -f && \
    ibmcloud plugin install observe-service -f && \
    if [[ "$TARGETPLATFORM" != "linux/arm64" ]]; then ibmcloud plugin install vpc-infrastructure -f; fi && \
    ibmcloud config --check-version=false && \
    chmod -R g=u ${HOME}

WORKDIR ${HOME}

VOLUME /workspaces

ENTRYPOINT ["/bin/sh"]
